[package]
name = "amplesamp-lang"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.1"
nom_locate = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
string-interner = "0.14.0"
thiserror = "1"
